#!/usr/bin/env bash

# abort if we're already inside a TMUX session
[ "$TMUX" == "" ] || exit 0

# present menu for the user to choose which workspace to open
PS3="Please choose your session: "
# shellcheck disable=SC2207
options=($(tmux list-sessions -F "#S" 2>/dev/null) "New Session" "Kill All")
echo "Available sessions"
echo "------------------"
echo " "
select opt in "${options[@]}"
do
    case $opt in
        "New Session")
            read -rp "Enter new session name (default_session if empty): " SESSION_NAME
			SESSION_NAME=${SESSION_NAME:-default_session_$(date +"%M%S")}
            tmux new -s "$SESSION_NAME"
            break
            ;;
        "Kill All")
            pkill -f tmux
            break;;
        *)
            tmux attach-session -t "$opt"
            break
            ;;
    esac
done

